/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registro;

import java.awt.*;
import Login.Login;
import menuPrincipal.menuPrincipal;

/**
 *
 * @author unai
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        registroIcono = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        nombreUsuario = new javax.swing.JTextField();
        enviarButton = new javax.swing.JPanel();
        enviarWord = new javax.swing.JLabel();
        incioSesionButton = new javax.swing.JPanel();
        inicioSesionWord = new javax.swing.JLabel();
        repetirPass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new Color(204, 204, 255));
        background.setForeground(new Color(204, 204, 204));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registro.png"))); // NOI18N
        background.add(registroIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 240, 190));

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setText("REGISTRO");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        mail.setForeground(new Color(204, 204, 204));
        mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mail.setText("Introduce un correo elecrónico");
        mail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mailMousePressed(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        background.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 340, 30));

        nombreUsuario.setForeground(new Color(204, 204, 204));
        nombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreUsuario.setText("Introduce un nombre de usuario");
        nombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreUsuarioMousePressed(evt);
            }
        });
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });
        background.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 340, 30));

        enviarButton.setBackground(new Color(255, 51, 153));
        enviarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enviarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarButtonMouseClicked(evt);
            }
        });
        enviarButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviarWord.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        enviarWord.setText("ENVIAR");
        enviarButton.add(enviarWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        background.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 240, 50));

        incioSesionButton.setBackground(new Color(204, 204, 255));
        incioSesionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        incioSesionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incioSesionButtonMouseClicked(evt);
            }
        });
        incioSesionButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioSesionWord.setText("¿Tienes cuenta? Entra");
        incioSesionButton.add(inicioSesionWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        background.add(incioSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 690, 190, 30));

        repetirPass.setForeground(new Color(204, 204, 204));
        repetirPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        repetirPass.setText("********");
        repetirPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        repetirPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repetirPassMousePressed(evt);
            }
        });
        background.add(repetirPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 340, 30));

        pass.setForeground(new Color(204, 204, 204));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setText("********");
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        background.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 340, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void incioSesionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incioSesionButtonMouseClicked
        this.dispose();
        Login inicioSesion = new Login();
        inicioSesion.setVisible(true);
    }//GEN-LAST:event_incioSesionButtonMouseClicked

    private void enviarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarButtonMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Se creará una cuenta con los datos.");
        this.dispose();
        menuPrincipal menuPrin = new menuPrincipal();
        menuPrin.setVisible(true);
    }//GEN-LAST:event_enviarButtonMouseClicked

    private void mailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMousePressed
        if (mail.getText().equals("Introduce un correo elecrónico")){
            mail.setText("");
            mail.setForeground(Color.black);
        }

        if (nombreUsuario.getText().isEmpty()){
            nombreUsuario.setText("Introduce un nombre de usuario");
            nombreUsuario.setForeground(Color.gray);
        }

        if (String.valueOf(pass.getPassword()).isEmpty() && String.valueOf(repetirPass.getPassword()).isEmpty()){
            pass.setText("********");
            repetirPass.setText("********");
            pass.setForeground(Color.gray);
            repetirPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_mailMousePressed

    private void nombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioMousePressed
        if (nombreUsuario.getText().equals("Introduce un nombre de usuario")){
            nombreUsuario.setText("");
            nombreUsuario.setForeground(Color.black);
        }

        if (mail.getText().isEmpty()){
            mail.setText("Introduce un correo electrónico");
            mail.setForeground(Color.gray);
        }

        if (String.valueOf(pass.getPassword()).isEmpty() && String.valueOf(repetirPass.getPassword()).isEmpty()){
            pass.setText("********");
            repetirPass.setText("********");
            pass.setForeground(Color.gray);
            repetirPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreUsuarioMousePressed

    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed
        if (String.valueOf(pass.getPassword()).equals("********")){
            pass.setText("");
            pass.setForeground(Color.black);
        }

        if (mail.getText().isEmpty()){
            mail.setText("Introduce un correo electrónico");
            mail.setForeground(Color.gray);
        }

        if (nombreUsuario.getText().isEmpty()){
            nombreUsuario.setText("Introduce un nombre de usuario");
            nombreUsuario.setForeground(Color.gray);
        }

        if (String.valueOf(repetirPass.getPassword()).isEmpty()){
            repetirPass.setText("********");
            repetirPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passMousePressed

    private void repetirPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repetirPassMousePressed
        if (String.valueOf(repetirPass.getPassword()).equals("********")){
            repetirPass.setText("");
            repetirPass.setForeground(Color.black);
        }

        if (mail.getText().isEmpty()){
            mail.setText("Introduce un correo electrónico");
            mail.setForeground(Color.gray);
        }

        if (nombreUsuario.getText().isEmpty()){
            nombreUsuario.setText("Introduce un nombre de usuario");
            nombreUsuario.setForeground(Color.gray);
        }

        if (String.valueOf(pass.getPassword()).isEmpty()){
            pass.setText("********");
            pass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_repetirPassMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel enviarButton;
    private javax.swing.JLabel enviarWord;
    private javax.swing.JPanel incioSesionButton;
    private javax.swing.JLabel inicioSesionWord;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel registroIcono;
    private javax.swing.JPasswordField repetirPass;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
