/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finPartida;

import menuPrincipal.menuPrincipal;

/**
 *
 * @author unai
 */
public class finPartida extends javax.swing.JFrame {
    private menuPrincipal menuPrin = new menuPrincipal();
    private String puntos = "Nada";
    /**
     * Creates new form finPartida
     */
    public finPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cerrarButton = new javax.swing.JPanel();
        cerrarWord = new javax.swing.JLabel();
        instagram = new javax.swing.JPanel();
        instagramIcono = new javax.swing.JLabel();
        twitter = new javax.swing.JPanel();
        twitterIcono = new javax.swing.JLabel();
        facebook = new javax.swing.JPanel();
        facebookIcono = new javax.swing.JLabel();
        puntuacionPanel = new javax.swing.JPanel();
        puntuación = new javax.swing.JLabel();
        puntuación1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(204, 204, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setText("¡COMPARTE TUS RESULTADOS!");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        cerrarButton.setBackground(new java.awt.Color(255, 51, 204));
        cerrarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseClicked(evt);
            }
        });
        cerrarButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrarWord.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        cerrarWord.setText("CERRAR");
        cerrarButton.add(cerrarWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        background.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 210, 70));

        instagram.setBackground(new java.awt.Color(204, 204, 255));
        instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                instagramMousePressed(evt);
            }
        });
        instagram.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instagramIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/instagram.png"))); // NOI18N
        instagram.add(instagramIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -50, -1, -1));

        background.add(instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 180, 150));

        twitter.setBackground(new java.awt.Color(204, 204, 255));
        twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
        });
        twitter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        twitterIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gorjeo.png"))); // NOI18N
        twitter.add(twitterIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 280, 250));

        background.add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 180, 150));

        facebook.setBackground(new java.awt.Color(204, 204, 255));
        facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
        });
        facebook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        facebookIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        facebook.add(facebookIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -50, -1, -1));

        background.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 180, 150));

        puntuacionPanel.setBackground(new java.awt.Color(204, 204, 255));
        puntuacionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        puntuacionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puntuación.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        puntuación.setText(puntos);
        puntuacionPanel.add(puntuación, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        background.add(puntuacionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, 150));

        puntuación1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        puntuación1.setText("Puntuación : ");
        background.add(puntuación1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPuntuacion(String points){
        puntos = points;
        System.out.println(puntos);
        this.puntuación.setText(puntos);
    }
    private void instagramMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "Subir puntuación a Instagram");
    }//GEN-LAST:event_instagramMousePressed

    private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Subir puntuación a Twitter");
    }//GEN-LAST:event_twitterMouseClicked

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Subir puntuación a Facebook");
    }//GEN-LAST:event_facebookMouseClicked

    private void cerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseClicked
        menuPrin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel cerrarButton;
    private javax.swing.JLabel cerrarWord;
    private javax.swing.JPanel facebook;
    private javax.swing.JLabel facebookIcono;
    private javax.swing.JPanel instagram;
    private javax.swing.JLabel instagramIcono;
    private javax.swing.JPanel puntuacionPanel;
    private javax.swing.JLabel puntuación;
    private javax.swing.JLabel puntuación1;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel twitter;
    private javax.swing.JLabel twitterIcono;
    // End of variables declaration//GEN-END:variables
}
